# Generated by Django 4.1.7 on 2023-04-13 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_location_project_host_project_payments_todate_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='remark',
            new_name='description',
        ),
    ]
