# Generated by Django 4.1.7 on 2023-04-13 11:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='authorized_users',
            field=models.ManyToManyField(blank=True, related_name='authorized_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
